SET NAMES utf8mb4;

CREATE TABLE courses (
    id VARCHAR(50) PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title_tr VARCHAR(255) NOT NULL,
    title_en VARCHAR(255) NOT NULL,
    color VARCHAR(32) NOT NULL,
    audience ENUM('common', 'department') NOT NULL,
    language VARCHAR(100) DEFAULT NULL,
    credits TINYINT UNSIGNED DEFAULT NULL,
    lecture_hours TINYINT UNSIGNED DEFAULT NULL,
    practice_hours TINYINT UNSIGNED DEFAULT NULL,
    lab_hours TINYINT UNSIGNED DEFAULT NULL,
    semester TINYINT UNSIGNED DEFAULT NULL,
    coordinator VARCHAR(255) DEFAULT NULL,
    summary_tr TEXT NULL,
    summary_en TEXT NULL,
    objectives_tr TEXT NULL,
    objectives_en TEXT NULL,
    description_tr TEXT NULL,
    description_en TEXT NULL,
    outcomes_tr TEXT NULL,
    outcomes_en TEXT NULL,
    prerequisites_tr TEXT NULL,
    prerequisites_en TEXT NULL,
    other_notes_tr TEXT NULL,
    other_notes_en TEXT NULL,
    textbook_tr TEXT NULL,
    textbook_en TEXT NULL,
    references_tr TEXT NULL,
    references_en TEXT NULL,
    section_name VARCHAR(120) DEFAULT NULL,
    crn VARCHAR(50) DEFAULT NULL,
    term_tr VARCHAR(120) DEFAULT NULL,
    term_en VARCHAR(120) DEFAULT NULL,
    start_date DATE DEFAULT NULL,
    end_date DATE DEFAULT NULL,
    last_access_date DATE DEFAULT NULL,
    instructors TEXT NULL,
    assistants TEXT NULL,
    schedule_tr TEXT NULL,
    schedule_en TEXT NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_courses_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE TABLE course_instructors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id VARCHAR(50) NOT NULL,
    user_id INT NOT NULL,
    role ENUM('COORDINATOR', 'INSTRUCTOR', 'ASSISTANT') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_course_user_role (course_id, user_id, role),
    INDEX idx_course_instructors_course_id (course_id),
    INDEX idx_course_instructors_user_id (user_id),
    INDEX idx_course_instructors_role (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE TABLE course_enrollments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id VARCHAR(50) NOT NULL,
    user_id INT NOT NULL,
    enrolled_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_course_user (course_id, user_id),
    INDEX idx_course_enrollments_course_id (course_id),
    INDEX idx_course_enrollments_user_id (user_id),
    CONSTRAINT fk_course_enrollments_course_id FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_enrollments_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_enrollments_enrolled_by FOREIGN KEY (enrolled_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE TABLE course_attendance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id VARCHAR(50) NOT NULL,
    user_id INT NOT NULL,
    week_number TINYINT UNSIGNED NOT NULL,
    is_present TINYINT(1) NULL DEFAULT NULL,
    marked_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_course_user_week (course_id, user_id, week_number),
    INDEX idx_course_attendance_course_id (course_id),
    INDEX idx_course_attendance_user_id (user_id),
    INDEX idx_course_attendance_week_number (week_number),
    CONSTRAINT fk_course_attendance_course_id FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_attendance_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_attendance_marked_by FOREIGN KEY (marked_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE TABLE course_grade_distributions (
    course_id VARCHAR(50) PRIMARY KEY,
    midterm_count TINYINT UNSIGNED NOT NULL DEFAULT 2,
    final_count TINYINT UNSIGNED NOT NULL DEFAULT 1,
    project_count TINYINT UNSIGNED NOT NULL DEFAULT 2,
    homework_count TINYINT UNSIGNED NOT NULL DEFAULT 14,
    quiz_count TINYINT UNSIGNED NOT NULL DEFAULT 14,
    midterm_weight TINYINT UNSIGNED NOT NULL DEFAULT 40,
    final_weight TINYINT UNSIGNED NOT NULL DEFAULT 30,
    project_weight TINYINT UNSIGNED NOT NULL DEFAULT 10,
    homework_weight TINYINT UNSIGNED NOT NULL DEFAULT 10,
    quiz_weight TINYINT UNSIGNED NOT NULL DEFAULT 10,
    updated_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_course_grade_distributions_course_id FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_grade_distributions_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE TABLE course_grade_scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id VARCHAR(50) NOT NULL,
    user_id INT NOT NULL,
    item_type ENUM('midterm', 'final', 'project', 'homework', 'quiz') NOT NULL,
    item_number TINYINT UNSIGNED NOT NULL,
    score DECIMAL(5,2) NULL DEFAULT NULL,
    updated_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_course_user_item (course_id, user_id, item_type, item_number),
    INDEX idx_course_grade_scores_course_id (course_id),
    INDEX idx_course_grade_scores_user_id (user_id),
    INDEX idx_course_grade_scores_item_type (item_type),
    CONSTRAINT fk_course_grade_scores_course_id FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_grade_scores_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_grade_scores_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;