CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role ENUM('ADMIN', 'INSTRUCTOR', 'STUDENT') NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

CREATE TABLE auth_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    last_used_at TIMESTAMP NULL DEFAULT NULL,
    revoked_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_auth_sessions_user_id (user_id),
    INDEX idx_auth_sessions_expires_at (expires_at),
    CONSTRAINT fk_auth_sessions_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

INSERT INTO users (email, password_hash, first_name, last_name, role, is_active) VALUES
('student@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Deneme', 'Ogrenci', 'STUDENT', TRUE),
('instructor@bitirme.local', '$2y$10$oWlH3FfgH0WsxDRL8UDzZOLuMk2z15ezw79cM1U1ybaCmSzt9Ydry', 'Deneme', 'Egitmen', 'INSTRUCTOR', TRUE),
('student01@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Ayşe', 'Yılmaz', 'STUDENT', TRUE),
('student02@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Mehmet', 'Demir', 'STUDENT', TRUE),
('student03@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Elif', 'Kaya', 'STUDENT', TRUE),
('student04@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Can', 'Şahin', 'STUDENT', TRUE),
('student05@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Zeynep', 'Çelik', 'STUDENT', TRUE),
('student06@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Ahmet', 'Yıldız', 'STUDENT', TRUE),
('student07@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Merve', 'Aydın', 'STUDENT', TRUE),
('student08@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Ömer', 'Koç', 'STUDENT', TRUE),
('student09@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Esra', 'Arslan', 'STUDENT', TRUE),
('student10@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Burak', 'Taş', 'STUDENT', TRUE),
('student11@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Seda', 'Kaplan', 'STUDENT', TRUE),
('student12@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Emre', 'Öztürk', 'STUDENT', TRUE),
('student13@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Derya', 'Güneş', 'STUDENT', TRUE),
('student14@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Hakan', 'Kılıç', 'STUDENT', TRUE),
('student15@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Nehir', 'Aslan', 'STUDENT', TRUE),
('student16@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Serkan', 'Polat', 'STUDENT', TRUE),
('student17@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'İrem', 'Özcan', 'STUDENT', TRUE),
('student18@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Onur', 'Erdoğan', 'STUDENT', TRUE),
('student19@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Selin', 'Acar', 'STUDENT', TRUE),
('student20@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Murat', 'Kara', 'STUDENT', TRUE),
('student21@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Ece', 'Doğan', 'STUDENT', TRUE),
('student22@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Kerem', 'Bulut', 'STUDENT', TRUE),
('student23@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Tuğba', 'Korkmaz', 'STUDENT', TRUE),
('student24@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Arda', 'Çetin', 'STUDENT', TRUE),
('student25@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Leyla', 'Aksoy', 'STUDENT', TRUE),
('student26@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Baran', 'Ergin', 'STUDENT', TRUE),
('student27@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Sıla', 'Yavuz', 'STUDENT', TRUE),
('student28@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Mert', 'Ünal', 'STUDENT', TRUE),
('student29@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Hilal', 'Eren', 'STUDENT', TRUE),
('student30@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Cem', 'Avcı', 'STUDENT', TRUE),
('student31@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Naz', 'Yalçın', 'STUDENT', TRUE),
('student32@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Kaan', 'Tekin', 'STUDENT', TRUE),
('student33@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Buse', 'Türkmen', 'STUDENT', TRUE),
('student34@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Tolga', 'Sarı', 'STUDENT', TRUE),
('student35@bitirme.local', '$2y$10$CWBJovvvcW1UumQ2GjIkKuS5esaxJWbCYwKDSsVJ1QMpUMG9X3p8C', 'Yasemin', 'Çavuş', 'STUDENT', TRUE);